require 'transform/controls/text'
require 'transform/controls/raw_data'
require 'transform/controls/subject/instance_receives_class'
require 'transform/controls/subject/transform'
require 'transform/controls/subject/transformer'
require 'transform/controls/subject'
require 'transform/controls/no_transformer'
require 'transform/controls/no_transform_methods'
